source 'http://rubygems.org'

gem 'rails', '~> 3'
gem 'thin'
gem 'unicorn'
gem 'bundler'
gem 'jquery-rails'
gem 'json'
gem 'haml'
gem 'capistrano', '2.15.5'
gem 'rvm-capistrano'
gem 'capistrano-unicorn'
gem 'less-rails-bootstrap'
gem 'therubyracer'
gem 'uglifier'
